// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBannerPlaceGenerated(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBannerPlaceGenerated(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBannerPlaceGenerated(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBannerPlaceGenerated(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBannerPlaceGenerated(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBannerPlaceGenerated(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum GradientType: Int {
  case linear = 0
  case radial = 1
  case sweep = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct BannerPlaceDecoration: Hashable {
  var bannerOffset: Int64
  var bannersGap: Int64
  var cornerRadius: Int64
  var loop: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerPlaceDecoration? {
    let bannerOffset = pigeonVar_list[0] as! Int64
    let bannersGap = pigeonVar_list[1] as! Int64
    let cornerRadius = pigeonVar_list[2] as! Int64
    let loop = pigeonVar_list[3] as! Bool

    return BannerPlaceDecoration(
      bannerOffset: bannerOffset,
      bannersGap: bannersGap,
      cornerRadius: cornerRadius,
      loop: loop
    )
  }
  func toList() -> [Any?] {
    return [
      bannerOffset,
      bannersGap,
      cornerRadius,
      loop,
    ]
  }
  static func == (lhs: BannerPlaceDecoration, rhs: BannerPlaceDecoration) -> Bool {
    return deepEqualsBannerPlaceGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBannerPlaceGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BannerDecorationDTO: Hashable {
  var color: Int64? = nil
  var image: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerDecorationDTO? {
    let color: Int64? = nilOrValue(pigeonVar_list[0])
    let image: String? = nilOrValue(pigeonVar_list[1])

    return BannerDecorationDTO(
      color: color,
      image: image
    )
  }
  func toList() -> [Any?] {
    return [
      color,
      image,
    ]
  }
  static func == (lhs: BannerDecorationDTO, rhs: BannerDecorationDTO) -> Bool {
    return deepEqualsBannerPlaceGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBannerPlaceGenerated(value: toList(), hasher: &hasher)
  }
}

private class BannerPlaceGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GradientType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return BannerPlaceDecoration.fromList(self.readValue() as! [Any?])
    case 131:
      return BannerDecorationDTO.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BannerPlaceGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GradientType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BannerPlaceDecoration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BannerDecorationDTO {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BannerPlaceGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BannerPlaceGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BannerPlaceGeneratedPigeonCodecWriter(data: data)
  }
}

class BannerPlaceGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BannerPlaceGeneratedPigeonCodec(readerWriter: BannerPlaceGeneratedPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BannerPlaceManagerHostApi {
  func loadBannerPlace(placeId: String) throws
  func preloadBannerPlace(placeId: String) throws
  func showNext(placeId: String) throws
  func showPrevious(placeId: String) throws
  func showByIndex(placeId: String, index: Int64) throws
  func pauseAutoscroll(placeId: String) throws
  func resumeAutoscroll(placeId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BannerPlaceManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BannerPlaceGeneratedPigeonCodec.shared }
  /// Sets up an instance of `BannerPlaceManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BannerPlaceManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.loadBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadBannerPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.loadBannerPlace(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadBannerPlaceChannel.setMessageHandler(nil)
    }
    let preloadBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.preloadBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preloadBannerPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.preloadBannerPlace(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      preloadBannerPlaceChannel.setMessageHandler(nil)
    }
    let showNextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showNext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showNextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.showNext(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showNextChannel.setMessageHandler(nil)
    }
    let showPreviousChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showPrevious\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPreviousChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.showPrevious(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showPreviousChannel.setMessageHandler(nil)
    }
    let showByIndexChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showByIndex\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showByIndexChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        let indexArg = args[1] as! Int64
        do {
          try api.showByIndex(placeId: placeIdArg, index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showByIndexChannel.setMessageHandler(nil)
    }
    let pauseAutoscrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.pauseAutoscroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseAutoscrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.pauseAutoscroll(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseAutoscrollChannel.setMessageHandler(nil)
    }
    let resumeAutoscrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.resumeAutoscroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeAutoscrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.resumeAutoscroll(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeAutoscrollChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BannerPlaceCallbackFlutterApiProtocol {
  func onBannerScroll(placeId placeIdArg: String, index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlaceLoaded(placeId placeIdArg: String, size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onActionWith(placeId placeIdArg: String, target targetArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlacePreloaded(placeId placeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlacePreloadedError(placeId placeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BannerPlaceCallbackFlutterApi: BannerPlaceCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BannerPlaceGeneratedPigeonCodec {
    return BannerPlaceGeneratedPigeonCodec.shared
  }
  func onBannerScroll(placeId placeIdArg: String, index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerScroll\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placeIdArg, indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlaceLoaded(placeId placeIdArg: String, size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlaceLoaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placeIdArg, sizeArg, widgetHeightArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onActionWith(placeId placeIdArg: String, target targetArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onActionWith\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placeIdArg, targetArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlacePreloaded(placeId placeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placeIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlacePreloadedError(placeId placeIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloadedError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([placeIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BannerLoadCallbackFlutterApiProtocol {
  func onBannersLoaded(size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BannerLoadCallbackFlutterApi: BannerLoadCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BannerPlaceGeneratedPigeonCodec {
    return BannerPlaceGeneratedPigeonCodec.shared
  }
  func onBannersLoaded(size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerLoadCallbackFlutterApi.onBannersLoaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sizeArg, widgetHeightArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BannerViewHostApi {
  func changeBannerPlaceId(newPlaceId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BannerViewHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BannerPlaceGeneratedPigeonCodec.shared }
  /// Sets up an instance of `BannerViewHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BannerViewHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let changeBannerPlaceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.changeBannerPlaceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeBannerPlaceIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let newPlaceIdArg = args[0] as! String
        do {
          try api.changeBannerPlaceId(newPlaceId: newPlaceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      changeBannerPlaceIdChannel.setMessageHandler(nil)
    }
  }
}
