// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum BannerPlaceGeneratedPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum GradientType: Int, CaseIterable {
  case linear = 0
  case radial = 1
  case sweep = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct BannerPlaceDecoration: Hashable, CustomStringConvertible {
  var bannerOffset: Int64
  var bannersGap: Int64
  var cornerRadius: Int64
  var loop: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerPlaceDecoration? {
    let bannerOffset = pigeonVar_list[0] as! Int64
    let bannersGap = pigeonVar_list[1] as! Int64
    let cornerRadius = pigeonVar_list[2] as! Int64
    let loop = pigeonVar_list[3] as! Bool

    return BannerPlaceDecoration(
      bannerOffset: bannerOffset,
      bannersGap: bannersGap,
      cornerRadius: cornerRadius,
      loop: loop
    )
  }
  func toList() -> [Any?] {
    return [
      bannerOffset,
      bannersGap,
      cornerRadius,
      loop,
    ]
  }
  static func == (lhs: BannerPlaceDecoration, rhs: BannerPlaceDecoration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.bannerOffset, rhs.bannerOffset) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.bannersGap, rhs.bannersGap) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.cornerRadius, rhs.cornerRadius) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.loop, rhs.loop)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BannerPlaceDecoration")
    BannerPlaceGeneratedPigeonInternal.deepHash(value: bannerOffset, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: bannersGap, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: cornerRadius, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: loop, hasher: &hasher)
  }

  public var description: String {
    return "BannerPlaceDecoration(bannerOffset: \(String(describing: bannerOffset)), bannersGap: \(String(describing: bannersGap)), cornerRadius: \(String(describing: cornerRadius)), loop: \(String(describing: loop)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BannerDecorationDTO: Hashable, CustomStringConvertible {
  var color: Int64? = nil
  var image: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerDecorationDTO? {
    let color: Int64? = nilOrValue(pigeonVar_list[0])
    let image: String? = nilOrValue(pigeonVar_list[1])

    return BannerDecorationDTO(
      color: color,
      image: image
    )
  }
  func toList() -> [Any?] {
    return [
      color,
      image,
    ]
  }
  static func == (lhs: BannerDecorationDTO, rhs: BannerDecorationDTO) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.color, rhs.color) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.image, rhs.image)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BannerDecorationDTO")
    BannerPlaceGeneratedPigeonInternal.deepHash(value: color, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: image, hasher: &hasher)
  }

  public var description: String {
    return "BannerDecorationDTO(color: \(String(describing: color)), image: \(String(describing: image)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BannerData: Hashable, CustomStringConvertible {
  var id: String? = nil
  var bannerPlace: String? = nil
  var payload: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BannerData? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let bannerPlace: String? = nilOrValue(pigeonVar_list[1])
    let payload: String? = nilOrValue(pigeonVar_list[2])

    return BannerData(
      id: id,
      bannerPlace: bannerPlace,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      bannerPlace,
      payload,
    ]
  }
  static func == (lhs: BannerData, rhs: BannerData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.id, rhs.id) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.bannerPlace, rhs.bannerPlace) && BannerPlaceGeneratedPigeonInternal.deepEquals(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BannerData")
    BannerPlaceGeneratedPigeonInternal.deepHash(value: id, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: bannerPlace, hasher: &hasher)
    BannerPlaceGeneratedPigeonInternal.deepHash(value: payload, hasher: &hasher)
  }

  public var description: String {
    return "BannerData(id: \(String(describing: id)), bannerPlace: \(String(describing: bannerPlace)), payload: \(String(describing: payload)))"
  }
}

private class BannerPlaceGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GradientType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return BannerPlaceDecoration.fromList(self.readValue() as! [Any?])
    case 131:
      return BannerDecorationDTO.fromList(self.readValue() as! [Any?])
    case 132:
      return BannerData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BannerPlaceGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GradientType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BannerPlaceDecoration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BannerDecorationDTO {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? BannerData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BannerPlaceGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BannerPlaceGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BannerPlaceGeneratedPigeonCodecWriter(data: data)
  }
}

class BannerPlaceGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BannerPlaceGeneratedPigeonCodec(readerWriter: BannerPlaceGeneratedPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BannerPlaceManagerHostApi {
  func loadBannerPlace(placeId: String) throws
  func reloadBannerPlace(placeId: String) throws
  func preloadBannerPlace(placeId: String) throws
  func showNext(placeId: String) throws
  func showPrevious(placeId: String) throws
  func showByIndex(placeId: String, index: Int64) throws
  func pauseAutoscroll(placeId: String) throws
  func resumeAutoscroll(placeId: String) throws
  func setInteraction(placeId: String, isInteractionEnabled: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BannerPlaceManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BannerPlaceGeneratedPigeonCodec.shared }
  /// Sets up an instance of `BannerPlaceManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BannerPlaceManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.loadBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadBannerPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.loadBannerPlace(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadBannerPlaceChannel.setMessageHandler(nil)
    }
    let reloadBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.reloadBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reloadBannerPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.reloadBannerPlace(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reloadBannerPlaceChannel.setMessageHandler(nil)
    }
    let preloadBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.preloadBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preloadBannerPlaceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.preloadBannerPlace(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      preloadBannerPlaceChannel.setMessageHandler(nil)
    }
    let showNextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showNext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showNextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.showNext(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showNextChannel.setMessageHandler(nil)
    }
    let showPreviousChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showPrevious\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showPreviousChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.showPrevious(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showPreviousChannel.setMessageHandler(nil)
    }
    let showByIndexChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showByIndex\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showByIndexChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        let indexArg = args[1] as! Int64
        do {
          try api.showByIndex(placeId: placeIdArg, index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showByIndexChannel.setMessageHandler(nil)
    }
    let pauseAutoscrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.pauseAutoscroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseAutoscrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.pauseAutoscroll(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseAutoscrollChannel.setMessageHandler(nil)
    }
    let resumeAutoscrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.resumeAutoscroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeAutoscrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        do {
          try api.resumeAutoscroll(placeId: placeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeAutoscrollChannel.setMessageHandler(nil)
    }
    let setInteractionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.setInteraction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setInteractionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placeIdArg = args[0] as! String
        let isInteractionEnabledArg = args[1] as! Bool
        do {
          try api.setInteraction(placeId: placeIdArg, isInteractionEnabled: isInteractionEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setInteractionChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BannerPlaceCallbackFlutterApiProtocol {
  func onBannerScroll(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlaceLoaded(size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onActionWith(bannerData bannerDataArg: BannerData, widgetEventName widgetEventNameArg: String, widgetData widgetDataArg: [String: Any?]?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlacePreloaded(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBannerPlacePreloadedError(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BannerPlaceCallbackFlutterApi: BannerPlaceCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BannerPlaceGeneratedPigeonCodec {
    return BannerPlaceGeneratedPigeonCodec.shared
  }
  func onBannerScroll(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerScroll\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlaceLoaded(size sizeArg: Int64, widgetHeight widgetHeightArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlaceLoaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sizeArg, widgetHeightArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onActionWith(bannerData bannerDataArg: BannerData, widgetEventName widgetEventNameArg: String, widgetData widgetDataArg: [String: Any?]?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onActionWith\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([bannerDataArg, widgetEventNameArg, widgetDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlacePreloaded(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBannerPlacePreloadedError(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloadedError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BannerViewHostApi {
  func changeBannerPlaceId(newPlaceId: String) throws
  func deInitBannerPlace() throws
  func setInteraction(isInteractionEnabled: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BannerViewHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BannerPlaceGeneratedPigeonCodec.shared }
  /// Sets up an instance of `BannerViewHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BannerViewHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let changeBannerPlaceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.changeBannerPlaceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeBannerPlaceIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let newPlaceIdArg = args[0] as! String
        do {
          try api.changeBannerPlaceId(newPlaceId: newPlaceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      changeBannerPlaceIdChannel.setMessageHandler(nil)
    }
    let deInitBannerPlaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.deInitBannerPlace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deInitBannerPlaceChannel.setMessageHandler { _, reply in
        do {
          try api.deInitBannerPlace()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deInitBannerPlaceChannel.setMessageHandler(nil)
    }
    let setInteractionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.setInteraction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setInteractionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isInteractionEnabledArg = args[0] as! Bool
        do {
          try api.setInteraction(isInteractionEnabled: isInteractionEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setInteractionChannel.setMessageHandler(nil)
    }
  }
}
