// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BannerPlaceGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

enum class GradientType(val raw: Int) {
  LINEAR(0),
  RADIAL(1),
  SWEEP(2);

  companion object {
    fun ofRaw(raw: Int): GradientType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BannerPlaceDecoration (
  val bannerOffset: Long,
  val bannersGap: Long,
  val cornerRadius: Long,
  val loop: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerPlaceDecoration {
      val bannerOffset = pigeonVar_list[0] as Long
      val bannersGap = pigeonVar_list[1] as Long
      val cornerRadius = pigeonVar_list[2] as Long
      val loop = pigeonVar_list[3] as Boolean
      return BannerPlaceDecoration(bannerOffset, bannersGap, cornerRadius, loop)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bannerOffset,
      bannersGap,
      cornerRadius,
      loop,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BannerPlaceDecoration) {
      return false
    }
    if (this === other) {
      return true
    }
    return BannerPlaceGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BannerDecorationDTO (
  val color: Long? = null,
  val image: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerDecorationDTO {
      val color = pigeonVar_list[0] as Long?
      val image = pigeonVar_list[1] as String?
      return BannerDecorationDTO(color, image)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      color,
      image,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BannerDecorationDTO) {
      return false
    }
    if (this === other) {
      return true
    }
    return BannerPlaceGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BannerPlaceGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GradientType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerPlaceDecoration.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerDecorationDTO.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GradientType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BannerPlaceDecoration -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BannerDecorationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BannerPlaceManagerHostApi {
  fun loadBannerPlace(placeId: String)
  fun preloadBannerPlace(placeId: String)
  fun showNext()
  fun showPrevious()
  fun showByIndex(index: Long)
  fun pauseAutoscroll()
  fun resumeAutoscroll()

  companion object {
    /** The codec used by BannerPlaceManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
    /** Sets up an instance of `BannerPlaceManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BannerPlaceManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.loadBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.loadBannerPlace(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.preloadBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.preloadBannerPlace(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showNext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.showNext()
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showPrevious$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.showPrevious()
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showByIndex$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val indexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.showByIndex(indexArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.pauseAutoscroll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pauseAutoscroll()
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.resumeAutoscroll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resumeAutoscroll()
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BannerPlaceCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BannerPlaceCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
  }
  fun onBannerScroll(indexArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerScroll$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(indexArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBannerPlaceLoaded(sizeArg: Long, widgetHeightArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlaceLoaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sizeArg, widgetHeightArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onActionWith(targetArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onActionWith$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(targetArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBannerPlacePreloaded(sizeArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sizeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BannerLoadCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BannerLoadCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
  }
  fun onBannersLoaded(sizeArg: Long, widgetHeightArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerLoadCallbackFlutterApi.onBannersLoaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sizeArg, widgetHeightArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
