// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BannerPlaceGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class GradientType(val raw: Int) {
  LINEAR(0),
  RADIAL(1),
  SWEEP(2);

  companion object {
    fun ofRaw(raw: Int): GradientType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BannerPlaceDecoration (
  val bannerOffset: Long,
  val bannersGap: Long,
  val cornerRadius: Long,
  val loop: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerPlaceDecoration {
      val bannerOffset = pigeonVar_list[0] as Long
      val bannersGap = pigeonVar_list[1] as Long
      val cornerRadius = pigeonVar_list[2] as Long
      val loop = pigeonVar_list[3] as Boolean
      return BannerPlaceDecoration(bannerOffset, bannersGap, cornerRadius, loop)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bannerOffset,
      bannersGap,
      cornerRadius,
      loop,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BannerPlaceDecoration
    return BannerPlaceGeneratedPigeonUtils.deepEquals(this.bannerOffset, other.bannerOffset) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.bannersGap, other.bannersGap) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.cornerRadius, other.cornerRadius) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.loop, other.loop)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.bannerOffset)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.bannersGap)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.cornerRadius)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.loop)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BannerDecorationDTO (
  val color: Long? = null,
  val image: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerDecorationDTO {
      val color = pigeonVar_list[0] as Long?
      val image = pigeonVar_list[1] as String?
      return BannerDecorationDTO(color, image)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      color,
      image,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BannerDecorationDTO
    return BannerPlaceGeneratedPigeonUtils.deepEquals(this.color, other.color) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.image, other.image)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.color)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.image)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BannerData (
  val id: String? = null,
  val bannerPlace: String? = null,
  val payload: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerData {
      val id = pigeonVar_list[0] as String?
      val bannerPlace = pigeonVar_list[1] as String?
      val payload = pigeonVar_list[2] as String?
      return BannerData(id, bannerPlace, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      bannerPlace,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BannerData
    return BannerPlaceGeneratedPigeonUtils.deepEquals(this.id, other.id) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.bannerPlace, other.bannerPlace) && BannerPlaceGeneratedPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.id)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.bannerPlace)
    result = 31 * result + BannerPlaceGeneratedPigeonUtils.deepHash(this.payload)
    return result
  }
}
private open class BannerPlaceGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GradientType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerPlaceDecoration.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerDecorationDTO.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GradientType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BannerPlaceDecoration -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BannerDecorationDTO -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BannerData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BannerPlaceManagerHostApi {
  fun loadBannerPlace(placeId: String)
  fun reloadBannerPlace(placeId: String)
  fun preloadBannerPlace(placeId: String)
  fun showNext(placeId: String)
  fun showPrevious(placeId: String)
  fun showByIndex(placeId: String, index: Long)
  fun pauseAutoscroll(placeId: String)
  fun resumeAutoscroll(placeId: String)

  companion object {
    /** The codec used by BannerPlaceManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
    /** Sets up an instance of `BannerPlaceManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BannerPlaceManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.loadBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.loadBannerPlace(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.reloadBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.reloadBannerPlace(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.preloadBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.preloadBannerPlace(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showNext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.showNext(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showPrevious$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.showPrevious(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.showByIndex$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val indexArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.showByIndex(placeIdArg, indexArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.pauseAutoscroll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.pauseAutoscroll(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerPlaceManagerHostApi.resumeAutoscroll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placeIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.resumeAutoscroll(placeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BannerPlaceCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BannerPlaceCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
  }
  fun onBannerScroll(indexArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerScroll$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(indexArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBannerPlaceLoaded(sizeArg: Long, widgetHeightArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlaceLoaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sizeArg, widgetHeightArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onActionWith(bannerDataArg: BannerData, widgetEventNameArg: String, widgetDataArg: Map<String, Any?>?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onActionWith$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(bannerDataArg, widgetEventNameArg, widgetDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBannerPlacePreloaded(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBannerPlacePreloadedError(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.BannerPlaceCallbackFlutterApi.onBannerPlacePreloadedError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BannerPlaceGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BannerViewHostApi {
  fun changeBannerPlaceId(newPlaceId: String)
  fun deInitBannerPlace()

  companion object {
    /** The codec used by BannerViewHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BannerPlaceGeneratedPigeonCodec()
    }
    /** Sets up an instance of `BannerViewHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BannerViewHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.changeBannerPlaceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val newPlaceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.changeBannerPlaceId(newPlaceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.inappstory_plugin.BannerViewHostApi.deInitBannerPlace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.deInitBannerPlace()
              listOf(null)
            } catch (exception: Throwable) {
              BannerPlaceGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
