// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CheckoutGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProductCartOffer (
  val offerId: String,
  val groupId: String? = null,
  val name: String,
  val description: String? = null,
  val url: String? = null,
  val coverUrl: String? = null,
  val imageUrls: List<String>,
  val currency: String? = null,
  val price: String? = null,
  val oldPrice: String? = null,
  val adult: Boolean? = null,
  val availability: Long,
  val size: String? = null,
  val color: String? = null,
  val quantity: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductCartOffer {
      val offerId = pigeonVar_list[0] as String
      val groupId = pigeonVar_list[1] as String?
      val name = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String?
      val url = pigeonVar_list[4] as String?
      val coverUrl = pigeonVar_list[5] as String?
      val imageUrls = pigeonVar_list[6] as List<String>
      val currency = pigeonVar_list[7] as String?
      val price = pigeonVar_list[8] as String?
      val oldPrice = pigeonVar_list[9] as String?
      val adult = pigeonVar_list[10] as Boolean?
      val availability = pigeonVar_list[11] as Long
      val size = pigeonVar_list[12] as String?
      val color = pigeonVar_list[13] as String?
      val quantity = pigeonVar_list[14] as Long
      return ProductCartOffer(offerId, groupId, name, description, url, coverUrl, imageUrls, currency, price, oldPrice, adult, availability, size, color, quantity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      offerId,
      groupId,
      name,
      description,
      url,
      coverUrl,
      imageUrls,
      currency,
      price,
      oldPrice,
      adult,
      availability,
      size,
      color,
      quantity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProductCartOffer) {
      return false
    }
    if (this === other) {
      return true
    }
    return CheckoutGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProductCart (
  val offers: List<ProductCartOffer>,
  val price: String,
  val oldPrice: String? = null,
  val priceCurrency: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductCart {
      val offers = pigeonVar_list[0] as List<ProductCartOffer>
      val price = pigeonVar_list[1] as String
      val oldPrice = pigeonVar_list[2] as String?
      val priceCurrency = pigeonVar_list[3] as String
      return ProductCart(offers, price, oldPrice, priceCurrency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      offers,
      price,
      oldPrice,
      priceCurrency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProductCart) {
      return false
    }
    if (this === other) {
      return true
    }
    return CheckoutGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CheckoutGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductCartOffer.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductCart.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProductCartOffer -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ProductCart -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CheckoutManagerCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CheckoutManagerCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutGeneratedPigeonCodec()
    }
  }
  fun onProductCartUpdate(offerArg: ProductCartOffer, callback: (Result<ProductCart>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutManagerCallbackFlutterApi.onProductCartUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(offerArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as ProductCart
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun getProductCartState(callback: (Result<ProductCart>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutManagerCallbackFlutterApi.getProductCartState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as ProductCart
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CheckoutCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CheckoutCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutGeneratedPigeonCodec()
    }
  }
  fun onProductCartClicked(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutCallbackFlutterApi.onProductCartClicked$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
