// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CheckoutGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProductCartOffer (
  val offerId: String,
  val groupId: String? = null,
  val name: String,
  val description: String? = null,
  val url: String? = null,
  val coverUrl: String? = null,
  val imageUrls: List<String>,
  val currency: String? = null,
  val price: String? = null,
  val oldPrice: String? = null,
  val adult: Boolean? = null,
  val availability: Long,
  val size: String? = null,
  val color: String? = null,
  val quantity: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductCartOffer {
      val offerId = pigeonVar_list[0] as String
      val groupId = pigeonVar_list[1] as String?
      val name = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String?
      val url = pigeonVar_list[4] as String?
      val coverUrl = pigeonVar_list[5] as String?
      val imageUrls = pigeonVar_list[6] as List<String>
      val currency = pigeonVar_list[7] as String?
      val price = pigeonVar_list[8] as String?
      val oldPrice = pigeonVar_list[9] as String?
      val adult = pigeonVar_list[10] as Boolean?
      val availability = pigeonVar_list[11] as Long
      val size = pigeonVar_list[12] as String?
      val color = pigeonVar_list[13] as String?
      val quantity = pigeonVar_list[14] as Long
      return ProductCartOffer(offerId, groupId, name, description, url, coverUrl, imageUrls, currency, price, oldPrice, adult, availability, size, color, quantity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      offerId,
      groupId,
      name,
      description,
      url,
      coverUrl,
      imageUrls,
      currency,
      price,
      oldPrice,
      adult,
      availability,
      size,
      color,
      quantity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProductCartOffer
    return CheckoutGeneratedPigeonUtils.deepEquals(this.offerId, other.offerId) && CheckoutGeneratedPigeonUtils.deepEquals(this.groupId, other.groupId) && CheckoutGeneratedPigeonUtils.deepEquals(this.name, other.name) && CheckoutGeneratedPigeonUtils.deepEquals(this.description, other.description) && CheckoutGeneratedPigeonUtils.deepEquals(this.url, other.url) && CheckoutGeneratedPigeonUtils.deepEquals(this.coverUrl, other.coverUrl) && CheckoutGeneratedPigeonUtils.deepEquals(this.imageUrls, other.imageUrls) && CheckoutGeneratedPigeonUtils.deepEquals(this.currency, other.currency) && CheckoutGeneratedPigeonUtils.deepEquals(this.price, other.price) && CheckoutGeneratedPigeonUtils.deepEquals(this.oldPrice, other.oldPrice) && CheckoutGeneratedPigeonUtils.deepEquals(this.adult, other.adult) && CheckoutGeneratedPigeonUtils.deepEquals(this.availability, other.availability) && CheckoutGeneratedPigeonUtils.deepEquals(this.size, other.size) && CheckoutGeneratedPigeonUtils.deepEquals(this.color, other.color) && CheckoutGeneratedPigeonUtils.deepEquals(this.quantity, other.quantity)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.offerId)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.groupId)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.name)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.description)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.url)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.coverUrl)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.imageUrls)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.currency)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.price)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.oldPrice)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.adult)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.availability)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.size)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.color)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.quantity)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProductCart (
  val offers: List<ProductCartOffer>,
  val price: String,
  val oldPrice: String? = null,
  val priceCurrency: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductCart {
      val offers = pigeonVar_list[0] as List<ProductCartOffer>
      val price = pigeonVar_list[1] as String
      val oldPrice = pigeonVar_list[2] as String?
      val priceCurrency = pigeonVar_list[3] as String
      return ProductCart(offers, price, oldPrice, priceCurrency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      offers,
      price,
      oldPrice,
      priceCurrency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProductCart
    return CheckoutGeneratedPigeonUtils.deepEquals(this.offers, other.offers) && CheckoutGeneratedPigeonUtils.deepEquals(this.price, other.price) && CheckoutGeneratedPigeonUtils.deepEquals(this.oldPrice, other.oldPrice) && CheckoutGeneratedPigeonUtils.deepEquals(this.priceCurrency, other.priceCurrency)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.offers)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.price)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.oldPrice)
    result = 31 * result + CheckoutGeneratedPigeonUtils.deepHash(this.priceCurrency)
    return result
  }
}
private open class CheckoutGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductCartOffer.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductCart.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProductCartOffer -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ProductCart -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CheckoutManagerCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CheckoutManagerCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutGeneratedPigeonCodec()
    }
  }
  fun onProductCartUpdate(offerArg: ProductCartOffer, callback: (Result<ProductCart>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutManagerCallbackFlutterApi.onProductCartUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(offerArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as ProductCart
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun getProductCartState(callback: (Result<ProductCart>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutManagerCallbackFlutterApi.getProductCartState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as ProductCart
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CheckoutCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CheckoutCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CheckoutGeneratedPigeonCodec()
    }
  }
  fun onProductCartClicked(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.inappstory_plugin.CheckoutCallbackFlutterApi.onProductCartClicked$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CheckoutGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
